name: Overall Project Euler

on: [push, pull_request, workflow_dispatch]

jobs:
  run-overall-test:
    name: Run Overall Test
    runs-on: self-hosted  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run script
        run: ./Overall_Project_Euler.py 
